# Generated by Django 2.1 on 2020-01-02 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('price', models.FloatField(null=True)),
                ('pic_file', models.CharField(max_length=500)),
                ('pic_url', models.URLField(max_length=500)),
                ('type', models.CharField(max_length=30)),
                ('sales', models.IntegerField()),
            ],
        ),
    ]
